version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: yoyo123
      POSTGRES_PASSWORD: 123123  
      POSTGRES_DB: postgres_avijoy
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
